spring:
    application:
        name: todo.group
    rabbitmq:
        host: woodpecker-01.rmq.cloudamqp.com
        port: 5672
        virtual-host: ${QUEUE_VHOST}
        username: ${QUEUE_USERNAME}
        password: ${QUEUE_PASSWORD}
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    security:
        cognito:
            token-url: ${COGNITO_TOKEN_URL}
            redirect-url: ${AUTH_REDIRECT_URL}
            client-id: ${COGNITO_CLIENT_ID}
            client_secret: ${COGNITO_CLIENT_SECRET}